---
name: node-ci

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x]
        platform:
          - os: ubuntu-latest
            shell: bash
          - os: macos-latest
            shell: bash
          - os: windows-latest
            shell: bash

    runs-on: ${{ matrix.os }}

    steps:
      # Checkout the repository
      - uses: actions/checkout@v2
        # Installs the specific version of Node.js
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run tests
        run: npm test
